/**
 * Zona dostave i geografski klaster po lokaciji — izvedeno iz LokacijeSection.tsx
 * (Zona 1 / Zona 2) i istraženih beogradskih opština. Koristi se za:
 *  - generisanje "Obližnje lokacije" bloka na /lokacija/[slug]/
 *  - FAQ odgovore koji zavise od zone dostave
 */

export const LOCATION_ZONE: Record<string, 1 | 2> = {
  "veliki-mokri-lug": 1,
  kaludjerica: 1,
  "mali-mokri-lug": 1,
  medakovic: 1,
  konjarnik: 1,
  "uciteljsko-naselje": 1,
  "lekino-brdo": 1,
  autokomanda: 1,
  vozdovac: 1,
  "vojvode-stepe": 1,
  "brace-jerkovic": 1,
  "vojvode-vlahovica": 1,
  "mitrovo-brdo": 1,
  "stepa-stepanovic": 1,
  kumodraz: 1,
  jajinci: 1,
  banjica: 1,
  zvezdara: 2,
  mirijevo: 2,
  karaburma: 2,
  palilula: 2,
  "slavujev-venac": 2,
  "vukov-spomenik": 2,
  djeram: 2,
  vracar: 2,
  cubura: 2,
  bogoslovija: 2,
  dorcol: 2,
  "stari-grad": 2,
  "novi-beograd": 2,
  zemun: 2,
  "bezanijska-kosa": 2,
  "cukaricka-padina": 2,
  senjak: 2,
  dedinje: 2,
  "savski-venac": 2,
  "banovo-brdo": 2,
  "golf-naselje": 2,
  zarkovo: 2,
  cerak: 2,
  vidikovac: 2,
  "filmski-grad": 2,
  rakovica: 2,
  miljakovac: 2,
  "kanarevo-brdo": 2,
};

// Geografski klaster (opština ili susedna grupa opština) — koristi se samo
// za grupisanje "obližnjih" lokacija radi internog linkovanja, nije prikazano kao tvrdnja o opštini.
export const LOCATION_AREA: Record<string, string> = {
  vozdovac: "vozdovac",
  medakovic: "vozdovac",
  konjarnik: "vozdovac",
  "uciteljsko-naselje": "vozdovac",
  "lekino-brdo": "vozdovac",
  autokomanda: "vozdovac",
  "vojvode-stepe": "vozdovac",
  "brace-jerkovic": "vozdovac",
  "vojvode-vlahovica": "vozdovac",
  "mitrovo-brdo": "vozdovac",
  "stepa-stepanovic": "vozdovac",
  kumodraz: "vozdovac",
  jajinci: "vozdovac",
  banjica: "vozdovac",

  zvezdara: "zvezdara",
  "veliki-mokri-lug": "zvezdara",
  "mali-mokri-lug": "zvezdara",
  mirijevo: "zvezdara",
  "vukov-spomenik": "zvezdara",
  djeram: "zvezdara",
  kaludjerica: "zvezdara",

  vracar: "centar",
  cubura: "centar",
  bogoslovija: "centar",
  "slavujev-venac": "centar",
  dorcol: "centar",
  "stari-grad": "centar",
  "savski-venac": "centar",
  senjak: "centar",
  dedinje: "centar",

  "novi-beograd": "novi-beograd",
  "bezanijska-kosa": "novi-beograd",
  zemun: "novi-beograd",

  palilula: "palilula",
  karaburma: "palilula",

  "cukaricka-padina": "cukarica",
  "banovo-brdo": "cukarica",
  "golf-naselje": "cukarica",
  zarkovo: "cukarica",
  cerak: "cukarica",
  vidikovac: "cukarica",
  "filmski-grad": "cukarica",
  "kanarevo-brdo": "cukarica",

  rakovica: "rakovica",
  miljakovac: "rakovica",
};
